import React,{useState} from 'react';
import {ArrowRight,CheckCircle2,X} from 'lucide-react';

const A={ [Symbol.toPrimitive]:()=> '/images/ngo-5.jpg?asset=' };
export const programs={
  '/st-patricks-academy/':{title:"St. Patrick's Academy",tag:'Education',intro:'Quality education for rural children',body:'St. Patrick’s Academy creates an innovative learning environment for children from poor and marginalized rural communities. The school helps students break cycles of poverty through academic excellence, character formation and opportunity.',gallery:'st-patricks',count:6},
  '/little-flower-school/':{title:'Little Flower School',tag:'Education',intro:'Opening doors through learning',body:'Little Flower School provides accessible education for children who would otherwise be excluded from the classroom. Your support supplies teachers, learning materials and a safe place where every child can thrive.',gallery:'little-flower',count:9},
  '/literacy-project/':{title:'Literacy Project',tag:'Education',intro:'A book can change a future',body:'Our literacy initiatives build reading skills, confidence and curiosity among rural children through libraries, after-school learning and community-based educational support.',gallery:'literacy',count:3},
  '/sponsorship/':{title:'Child Sponsorship',tag:'Programs',intro:'One connection. Lifelong impact.',body:'Sponsorship helps a child receive education, nutritious meals, school supplies and the steady encouragement needed to build a brighter future.',gallery:'st-patricks',count:4},
  '/community-health/':{title:'Community Health',tag:'Programs',intro:'Healthcare with dignity',body:'Mobile clinics, health camps and preventive care bring essential medical support to people living far from reliable healthcare. More than a thousand patients receive treatment each month.',gallery:'community-health',count:6},
  '/women-empowerment/':{title:'Women Empowerment',tag:'Programs',intro:'Strong women build strong communities',body:'Self-help groups, vocational opportunities and small-business support help women achieve financial independence, leadership and dignity.',gallery:'women-empowerment',count:6},
  '/outreach/':{title:'Community Outreach',tag:'Programs',intro:'Standing beside those left behind',body:'Our outreach responds to urgent needs among widows, families and vulnerable villages through housing, food security and compassionate community support.',gallery:'outreach',count:3},
  '/vocational-training/':{title:'Vocational Training',tag:'Programs',intro:'Skills that create independence',body:'Practical training in tailoring, technology and trades equips young adults and women with marketable skills, confidence and pathways to sustainable income.',gallery:'vocational-training',count:6},
  '/drinking-water/':{title:'Drinking Water',tag:'Programs',intro:'Clean water changes everything',body:'Borewells bring safe drinking water close to homes, reduce waterborne illness and return hours of each day to women and children in underserved villages.',gallery:'drinking-water-project',count:4},
};

const staticPages={
  '/where-we-work/':['Where We Work','About us','Rooted in rural India','People Action Development Society supports marginalized communities across Tamil Nadu and neighboring regions, partnering with trusted local leaders to deliver sustainable programs in education, health, clean water and economic opportunity.','2024/09/ds-where-we-work-scaled.webp'],
  '/legacy-gift/':['Leave a Legacy','Get involved','Make compassion part of your legacy','A planned gift can create opportunities for generations. Include People Action Development Society in your will, trust, retirement plan or life insurance beneficiary designation.','2024/09/ds-home-bg-e-scaled.webp'],
  '/fiscal-sponsor/':['Fiscal Sponsorship','Partnerships','Turn a promising idea into impact','Our fiscal sponsorship program supports charitable initiatives aligned with our mission by providing nonprofit oversight, administrative support and a trusted framework for fundraising.','2024/10/ds-home-bg-m.webp'],
  '/tribute/':['In Loving Tribute','About us','Lives that continue to inspire','We remember the compassionate friends whose generosity and service helped restore dignity and hope in countless lives. Their legacy continues through every child and community they touched.','2024/10/ds-img-tribute-william-parker.webp'],
};

function Title({tag,title,intro,image}){return <section className="pageHero" style={{backgroundImage:`linear-gradient(90deg,#102c36de,#102c3660),url(${image})`}}><div className="wrap"><p className="eyebrow light">{tag}</p><h1>{title}</h1><p>{intro}</p></div></section>}
const staticImage=title=>title.includes('Where')?'/images/volunteer-action.png':title.includes('Legacy')?'/images/education-community.png':'/images/ngo-leadership.png';
const contentImage=key=>key.includes('health')||key.includes('water')?'/images/health-water-community.png':key.includes('women')||key.includes('vocational')||key.includes('outreach')||key.includes('volunteer')?'/images/women-livelihoods.png':'/images/education-community.png';
const galleryImages=(key,n)=>Array.from({length:n},(_,i)=>contentImage(key)+'?view='+i);

export function ProgramPage({data}){let images=galleryImages(data.gallery,data.count);return <main><Title tag={data.tag} title={data.title} intro={data.intro} image={images[0]}/><section className="section"><div className="wrap detailGrid"><div><p className="eyebrow">Our commitment</p><h2>{data.intro}</h2><p className="lead">{data.body}</p><p>Every program is shaped with local communities and designed around dignity, accountability and long-term impact. Contributions directly support people and projects on the ground.</p><a className="btn orange" href="/make-your-contribution/">Support this program <ArrowRight size={17}/></a></div><aside><b>95%</b><span>of every donation supports programs</span><hr/><b>25+</b><span>years of sustained service</span></aside></div></section><ImageGallery images={images}/></main>}

export function StaticPage({data}){return <main><Title title={data[0]} tag={data[1]} intro={data[2]} image={staticImage(data[0])}/><section className="section"><div className="wrap narrow"><p className="eyebrow">Our mission</p><h2>{data[2]}</h2><p className="lead">{data[3]}</p><p>We believe meaningful change happens through partnership, transparency and sustained care. Together, supporters and local communities transform opportunity into lasting progress.</p><a href="/contact-us/" className="btn orange">Contact us <ArrowRight size={17}/></a></div></section></main>}

export function ImageGallery({images=galleryImages('community-health',6)}){const [view,setView]=useState(null);return <section className="section galleryPage"><div className="wrap"><p className="eyebrow center">Life in pictures</p><h2 className="center">Stories of <em>impact</em></h2><div className="galleryGrid">{images.map((x,i)=><button onClick={()=>setView(x)} key={x}><img src={x} onError={e=>e.currentTarget.closest('button').style.display='none'} /><span>View image</span></button>)}</div></div>{view&&<div className="lightbox" onClick={()=>setView(null)}><button><X/></button><img src={view}/></div>}</section>}

export function GalleryPage(){const [filter,setFilter]=useState('community-health');let groups=['community-health','women-empowerment','st-patricks','vocational-training'];return <main><Title tag="Our work" title="Gallery" intro="Moments of dignity, joy and transformation" image={'/images/women-livelihoods.png'}/><div className="filterbar">{groups.map(g=><button className={filter===g?'active':''} onClick={()=>setFilter(g)} key={g}>{g.replaceAll('-',' ')}</button>)}</div><ImageGallery images={galleryImages(filter,6)}/></main>}

export function Leadership(){let people=[['Dr. Meera Nair','Executive Director','/images/leader-meera-nair.png'],['Ravi Menon','Programs Lead','/images/leader-ravi-menon.png'],['Priya Joseph','Community Partnerships','/images/leader-priya-joseph.png']];return <main><Title tag="About us" title="Leadership" intro="People united by compassion and purpose" image="/images/ngo-leadership.png"/><section className="section"><div className="wrap leadershipIntro"><img src="/images/ngo-leadership.png"/><div><p className="eyebrow">Working together</p><h2>Leadership rooted in <em>community</em></h2><p className="lead">Our team combines local experience, professional skill and a shared commitment to accountable development.</p></div></div><div className="wrap roleGrid">{people.map(p=><article key={p[0]}><img src={p[2]} alt={p[0]}/><div><p className="eyebrow">{p[1]}</p><h3>{p[0]}</h3></div></article>)}</div></section></main>}

export function FormPage({kind='contact'}){const [sent,setSent]=useState(false);const submit=e=>{e.preventDefault();setSent(true);scrollTo({top:0,behavior:'smooth'})};let volunteer=kind==='volunteer';return <main><Title tag="Get involved" title={volunteer?'Become a Volunteer':'Contact Us'} intro={volunteer?'Share your time and talent':'We would love to hear from you'} image={volunteer?"/images/volunteer-action.png":"/images/ngo-leadership.png"}/><section className="section"><div className="wrap formGrid"><div><p className="eyebrow">Start a conversation</p><h2>{volunteer?'Your skills can create change':'Let’s connect'}</h2><p>Complete the form and our team will follow up. Required fields are marked clearly.</p><p><b>Email</b><br/>hello@padsngo.org</p><p><b>Phone</b><br/>+91 98765 43210</p></div>{sent?<div className="success"><CheckCircle2/><h3>Thank you!</h3><p>Your information was validated and recorded in this demo. Connect an email provider to deliver submissions to the organization.</p><button className="btn orange" onClick={()=>setSent(false)}>Send another</button></div>:<form className="contactForm" onSubmit={submit}><label>Full name<input required name="name"/></label><label>Email address<input required type="email" name="email"/></label>{volunteer&&<label>Area of interest<select required defaultValue=""><option value="" disabled>Select one</option><option>Education</option><option>Fundraising</option><option>Community outreach</option><option>Professional services</option></select></label>}<label>Phone<input type="tel" name="phone"/></label><label className="full">Message<textarea required rows="5"/></label><button className="btn orange">Submit <ArrowRight size={17}/></button></form>}</div></section></main>}

export function DonatePage(){const [amount,setAmount]=useState(50),[monthly,setMonthly]=useState(false),[done,setDone]=useState(false);return <main><Title tag="Give hope" title="Make Your Contribution" intro="Your generosity becomes a lifeline" image={'/images/education-community.png'}/><section className="section donationPage"><div className="wrap donateGrid"><div><p className="eyebrow">Your impact</p><h2>Every gift <em>matters</em></h2><p className="lead">95% of donations support programs that educate children, treat patients, empower women and provide clean water.</p><ul><li><CheckCircle2/> Secure payment integration ready</li><li><CheckCircle2/> Tax-deductible contribution</li><li><CheckCircle2/> One-time or monthly support</li></ul></div>{done?<div className="success"><CheckCircle2/><h3>Donation checkout ready</h3><p>You selected a {monthly?'monthly':'one-time'} gift of ${amount}. A Stripe or PayPal account is required to process a real transaction.</p><button className="btn orange" onClick={()=>setDone(false)}>Change gift</button></div>:<form className="donateBox" onSubmit={e=>{e.preventDefault();setDone(true)}}><div className="frequency"><button type="button" className={!monthly?'active':''} onClick={()=>setMonthly(false)}>One time</button><button type="button" className={monthly?'active':''} onClick={()=>setMonthly(true)}>Monthly</button></div><label>Choose an amount</label><div className="amounts">{[25,50,100,250].map(x=><button type="button" className={amount===x?'active':''} onClick={()=>setAmount(x)}>${x}</button>)}</div><label>Custom amount<input type="number" min="5" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="btn orange fullBtn">Continue to payment <ArrowRight size={17}/></button><small>Demo checkout — no payment will be charged.</small></form>}</div></section></main>}

export function Accountability(){return <main><Title tag="About us" title="Accountability" intro="Your trust is our responsibility" image={'/images/ngo-leadership.png'}/><section className="section"><div className="wrap detailGrid"><div><p className="eyebrow">Transparent stewardship</p><h2>95% supports our <em>programs</em></h2><p className="lead">We are committed to financial transparency, responsible governance and measurable community impact.</p><p>People Action Development Society is a registered nonprofit organization.</p></div><img className="accountabilityImage" src="/images/ngo-leadership.png"/></div></section></main>}

export function MediaPage(){return <main><Title tag="News & stories" title="In the Media" intro="Recognition that amplifies unheard voices" image={'/images/media-interview.png'}/><section className="section"><div className="wrap newsList">{['Legacy of Late St. Bernard Parish Teen Lives On','Global Activism: Improving the Lives of Community Development','Next-door saint of marginalized and disadvantaged','A Mission of Hope','Mission Matters Live'].map((x,i)=><article><span>0{i+1}</span><div><p className="eyebrow">Press feature</p><h3>{x}</h3><p>Stories and interviews recognizing the work of People Action Development Society and the communities we serve.</p></div><ArrowRight/></article>)}</div></section></main>}

export function Newsletter(){const [ok,setOk]=useState(false);return <main><Title tag="Stay connected" title="Newsletter" intro="Stories of hope delivered to your inbox" image={'/images/education-community.png'}/><section className="section"><div className="wrap narrow center"><p className="eyebrow">Join our community</p><h2>See your impact <em>unfold</em></h2><p>Receive field updates, volunteer stories and new ways to take action.</p>{ok?<div className="success compact"><CheckCircle2/><h3>You’re subscribed!</h3></div>:<form className="subscribe" onSubmit={e=>{e.preventDefault();setOk(true)}}><input type="email" required placeholder="Your email address"/><button className="btn orange">Subscribe</button></form>}</div></section></main>}

export function PageRouter({Home}){let path=window.location.pathname;if(path==='/')return <Home/>;if(programs[path])return <ProgramPage data={programs[path]}/>;if(staticPages[path])return <StaticPage data={staticPages[path]}/>;if(path==='/gallery/')return <GalleryPage/>;if(path==='/leadership/')return <Leadership/>;if(path==='/contact-us/')return <FormPage/>;if(path==='/volunteer/')return <FormPage kind="volunteer"/>;if(path==='/make-your-contribution/'||path==='/donating-methods/')return <DonatePage/>;if(path==='/accountability/')return <Accountability/>;if(path==='/in-the-media/')return <MediaPage/>;if(path==='/newsletter/')return <Newsletter/>;return <StaticPage data={[path.split('/')[1]?.replaceAll('-',' ')||'Page','People Action Development Society','Working together for dignity and hope','This page is part of People Action Development Society’s mission to empower poor and marginalized communities through sustainable, community-led action.','2024/09/ds-home-bg-e-scaled.webp']}/>}
